name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  go_router: ^6.5.2
  path_provider: ^2.1.1
  # I/O Packages
  # Http Request Manager
  dio: ^5.3.3
  # Reuse the previous calls to debug or check from broken calls
  curl_logger_dio_interceptor: ^1.0.0
  # Caching Package for Dio Manager
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  # Clean way to view your request
  pretty_dio_logger: ^1.3.1
  # Cookie Manager
  dio_cookie_manager: ^3.1.1
  #
  dio_http2_adapter: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner:
  freezed: ^2.4.5
  freezed_annotation: ^2.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/icons-24.png
    - assets/page-1/images/cellular-connection.png
    - assets/page-1/images/icons-24-jFQ.png
    - assets/page-1/images/person.png
    - assets/page-1/images/icons-24-gcS.png
    - assets/page-1/images/icons-24-wXx.png
    - assets/page-1/images/categpryselectionicons.png
    - assets/page-1/images/icons-24-jnS.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/categpryselectionicons-dMc.png
    - assets/page-1/images/icons-24-eae.png
    - assets/page-1/images/home.png
    - assets/page-1/images/categpryselectionicons-2eN.png
    - assets/page-1/images/icons-24-dxe.png
    - assets/page-1/images/wifi-cMx.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/categpryselectionicons-Ymp.png
    - assets/page-1/images/supportagent.png
    - assets/page-1/images/cellular-connection-oqL.png
    - assets/page-1/images/dashboardcustomize.png
    - assets/page-1/images/dashboardcustomize-pw4.png
    - assets/page-1/images/categpryselectionicons-wNi.png
    - assets/page-1/images/home-p7k.png
    - assets/page-1/images/emptystate.png
    - assets/page-1/images/battery-Gpr.png
    - assets/page-1/images/supportagent-k9Q.png
    - assets/page-1/images/person-RmL.png
    - assets/page-1/images/image.png
    - assets/page-1/images/image-qkv.png
    - assets/page-1/images/image-EMg.png
    - assets/page-1/images/image-mHU.png
    - assets/page-1/images/man-presentation-miniature-building.png
    - assets/page-1/images/man-presentation-miniature-building-rq8.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
